/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface GrazingRangeInterface extends ethers.utils.Interface {
  functions: {
    "addCampaignInfo(address,address,uint256)": FunctionFragment;
    "addRewardInfo(uint256,uint256,uint256)": FunctionFragment;
    "campaignInfo(uint256)": FunctionFragment;
    "campaignInfoLen()": FunctionFragment;
    "campaignRewardInfo(uint256,uint256)": FunctionFragment;
    "currentEndBlock(uint256)": FunctionFragment;
    "currentRewardPerBlock(uint256)": FunctionFragment;
    "deposit(uint256,uint256)": FunctionFragment;
    "emergencyRewardWithdraw(uint256,uint256,address)": FunctionFragment;
    "emergencyWithdraw(uint256)": FunctionFragment;
    "getMultiplier(uint256,uint256,uint256)": FunctionFragment;
    "harvest(uint256[])": FunctionFragment;
    "initialize(address)": FunctionFragment;
    "massUpdateCampaigns()": FunctionFragment;
    "owner()": FunctionFragment;
    "pendingReward(uint256,address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "rewardHolder()": FunctionFragment;
    "rewardInfoLen(uint256)": FunctionFragment;
    "rewardInfoLimit()": FunctionFragment;
    "setRewardHolder(address)": FunctionFragment;
    "setRewardInfoLimit(uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateCampaign(uint256)": FunctionFragment;
    "userInfo(uint256,address)": FunctionFragment;
    "withdraw(uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addCampaignInfo",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addRewardInfo",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignInfoLen",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "campaignRewardInfo",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "currentEndBlock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "currentRewardPerBlock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyRewardWithdraw",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMultiplier",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "harvest",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "initialize", values: [string]): string;
  encodeFunctionData(
    functionFragment: "massUpdateCampaigns",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingReward",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardHolder",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardInfoLen",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardInfoLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setRewardHolder",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setRewardInfoLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userInfo",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addCampaignInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addRewardInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignInfoLen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignRewardInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentEndBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentRewardPerBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyRewardWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "harvest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "massUpdateCampaigns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardHolder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardInfoLen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardInfoLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRewardHolder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRewardInfoLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userInfo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "AddCampaignInfo(uint256,address,address,uint256)": EventFragment;
    "AddRewardInfo(uint256,uint256,uint256,uint256)": EventFragment;
    "Deposit(address,uint256,uint256)": EventFragment;
    "EmergencyWithdraw(address,uint256,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "SetRewardHolder(address)": EventFragment;
    "SetRewardInfoLimit(uint256)": EventFragment;
    "Withdraw(address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AddCampaignInfo"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AddRewardInfo"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Deposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EmergencyWithdraw"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetRewardHolder"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetRewardInfoLimit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdraw"): EventFragment;
}

export class GrazingRange extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: GrazingRangeInterface;

  functions: {
    addCampaignInfo(
      _stakingToken: string,
      _rewardToken: string,
      _startBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addCampaignInfo(address,address,uint256)"(
      _stakingToken: string,
      _rewardToken: string,
      _startBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    addRewardInfo(
      _campaignID: BigNumberish,
      _endBlock: BigNumberish,
      _rewardPerBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addRewardInfo(uint256,uint256,uint256)"(
      _campaignID: BigNumberish,
      _endBlock: BigNumberish,
      _rewardPerBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    campaignInfo(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        stakingToken: string;
        rewardToken: string;
        startBlock: BigNumber;
        lastRewardBlock: BigNumber;
        accRewardPerShare: BigNumber;
        totalStaked: BigNumber;
        totalRewards: BigNumber;
      }
    >;

    "campaignInfo(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        stakingToken: string;
        rewardToken: string;
        startBlock: BigNumber;
        lastRewardBlock: BigNumber;
        accRewardPerShare: BigNumber;
        totalStaked: BigNumber;
        totalRewards: BigNumber;
      }
    >;

    campaignInfoLen(overrides?: CallOverrides): Promise<[BigNumber]>;

    "campaignInfoLen()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    campaignRewardInfo(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        endBlock: BigNumber;
        rewardPerBlock: BigNumber;
      }
    >;

    "campaignRewardInfo(uint256,uint256)"(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        endBlock: BigNumber;
        rewardPerBlock: BigNumber;
      }
    >;

    currentEndBlock(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "currentEndBlock(uint256)"(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    currentRewardPerBlock(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "currentRewardPerBlock(uint256)"(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    deposit(
      _campaignID: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "deposit(uint256,uint256)"(
      _campaignID: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    emergencyRewardWithdraw(
      _campaignID: BigNumberish,
      _amount: BigNumberish,
      _beneficiary: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "emergencyRewardWithdraw(uint256,uint256,address)"(
      _campaignID: BigNumberish,
      _amount: BigNumberish,
      _beneficiary: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    emergencyWithdraw(
      _campaignID: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "emergencyWithdraw(uint256)"(
      _campaignID: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getMultiplier(
      _from: BigNumberish,
      _to: BigNumberish,
      _endBlock: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getMultiplier(uint256,uint256,uint256)"(
      _from: BigNumberish,
      _to: BigNumberish,
      _endBlock: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    harvest(
      _campaignIDs: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "harvest(uint256[])"(
      _campaignIDs: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    initialize(
      _rewardHolder: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(address)"(
      _rewardHolder: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    massUpdateCampaigns(overrides?: Overrides): Promise<ContractTransaction>;

    "massUpdateCampaigns()"(
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    pendingReward(
      _campaignID: BigNumberish,
      _user: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "pendingReward(uint256,address)"(
      _campaignID: BigNumberish,
      _user: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    rewardHolder(overrides?: CallOverrides): Promise<[string]>;

    "rewardHolder()"(overrides?: CallOverrides): Promise<[string]>;

    rewardInfoLen(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "rewardInfoLen(uint256)"(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    rewardInfoLimit(overrides?: CallOverrides): Promise<[BigNumber]>;

    "rewardInfoLimit()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    setRewardHolder(
      _rewardHolder: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setRewardHolder(address)"(
      _rewardHolder: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setRewardInfoLimit(
      _updatedRewardInfoLimit: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setRewardInfoLimit(uint256)"(
      _updatedRewardInfoLimit: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    updateCampaign(
      _campaignID: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "updateCampaign(uint256)"(
      _campaignID: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    userInfo(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { amount: BigNumber; rewardDebt: BigNumber }
    >;

    "userInfo(uint256,address)"(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { amount: BigNumber; rewardDebt: BigNumber }
    >;

    withdraw(
      _campaignID: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "withdraw(uint256,uint256)"(
      _campaignID: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  addCampaignInfo(
    _stakingToken: string,
    _rewardToken: string,
    _startBlock: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addCampaignInfo(address,address,uint256)"(
    _stakingToken: string,
    _rewardToken: string,
    _startBlock: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  addRewardInfo(
    _campaignID: BigNumberish,
    _endBlock: BigNumberish,
    _rewardPerBlock: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addRewardInfo(uint256,uint256,uint256)"(
    _campaignID: BigNumberish,
    _endBlock: BigNumberish,
    _rewardPerBlock: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  campaignInfo(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
      stakingToken: string;
      rewardToken: string;
      startBlock: BigNumber;
      lastRewardBlock: BigNumber;
      accRewardPerShare: BigNumber;
      totalStaked: BigNumber;
      totalRewards: BigNumber;
    }
  >;

  "campaignInfo(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
      stakingToken: string;
      rewardToken: string;
      startBlock: BigNumber;
      lastRewardBlock: BigNumber;
      accRewardPerShare: BigNumber;
      totalStaked: BigNumber;
      totalRewards: BigNumber;
    }
  >;

  campaignInfoLen(overrides?: CallOverrides): Promise<BigNumber>;

  "campaignInfoLen()"(overrides?: CallOverrides): Promise<BigNumber>;

  campaignRewardInfo(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { endBlock: BigNumber; rewardPerBlock: BigNumber }
  >;

  "campaignRewardInfo(uint256,uint256)"(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { endBlock: BigNumber; rewardPerBlock: BigNumber }
  >;

  currentEndBlock(
    _campaignID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "currentEndBlock(uint256)"(
    _campaignID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  currentRewardPerBlock(
    _campaignID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "currentRewardPerBlock(uint256)"(
    _campaignID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  deposit(
    _campaignID: BigNumberish,
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "deposit(uint256,uint256)"(
    _campaignID: BigNumberish,
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  emergencyRewardWithdraw(
    _campaignID: BigNumberish,
    _amount: BigNumberish,
    _beneficiary: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "emergencyRewardWithdraw(uint256,uint256,address)"(
    _campaignID: BigNumberish,
    _amount: BigNumberish,
    _beneficiary: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  emergencyWithdraw(
    _campaignID: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "emergencyWithdraw(uint256)"(
    _campaignID: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getMultiplier(
    _from: BigNumberish,
    _to: BigNumberish,
    _endBlock: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getMultiplier(uint256,uint256,uint256)"(
    _from: BigNumberish,
    _to: BigNumberish,
    _endBlock: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  harvest(
    _campaignIDs: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "harvest(uint256[])"(
    _campaignIDs: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  initialize(
    _rewardHolder: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(address)"(
    _rewardHolder: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  massUpdateCampaigns(overrides?: Overrides): Promise<ContractTransaction>;

  "massUpdateCampaigns()"(overrides?: Overrides): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  pendingReward(
    _campaignID: BigNumberish,
    _user: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "pendingReward(uint256,address)"(
    _campaignID: BigNumberish,
    _user: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  rewardHolder(overrides?: CallOverrides): Promise<string>;

  "rewardHolder()"(overrides?: CallOverrides): Promise<string>;

  rewardInfoLen(
    _campaignID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "rewardInfoLen(uint256)"(
    _campaignID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  rewardInfoLimit(overrides?: CallOverrides): Promise<BigNumber>;

  "rewardInfoLimit()"(overrides?: CallOverrides): Promise<BigNumber>;

  setRewardHolder(
    _rewardHolder: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setRewardHolder(address)"(
    _rewardHolder: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setRewardInfoLimit(
    _updatedRewardInfoLimit: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setRewardInfoLimit(uint256)"(
    _updatedRewardInfoLimit: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  updateCampaign(
    _campaignID: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "updateCampaign(uint256)"(
    _campaignID: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  userInfo(
    arg0: BigNumberish,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { amount: BigNumber; rewardDebt: BigNumber }
  >;

  "userInfo(uint256,address)"(
    arg0: BigNumberish,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { amount: BigNumber; rewardDebt: BigNumber }
  >;

  withdraw(
    _campaignID: BigNumberish,
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "withdraw(uint256,uint256)"(
    _campaignID: BigNumberish,
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    addCampaignInfo(
      _stakingToken: string,
      _rewardToken: string,
      _startBlock: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "addCampaignInfo(address,address,uint256)"(
      _stakingToken: string,
      _rewardToken: string,
      _startBlock: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    addRewardInfo(
      _campaignID: BigNumberish,
      _endBlock: BigNumberish,
      _rewardPerBlock: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "addRewardInfo(uint256,uint256,uint256)"(
      _campaignID: BigNumberish,
      _endBlock: BigNumberish,
      _rewardPerBlock: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    campaignInfo(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        stakingToken: string;
        rewardToken: string;
        startBlock: BigNumber;
        lastRewardBlock: BigNumber;
        accRewardPerShare: BigNumber;
        totalStaked: BigNumber;
        totalRewards: BigNumber;
      }
    >;

    "campaignInfo(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        stakingToken: string;
        rewardToken: string;
        startBlock: BigNumber;
        lastRewardBlock: BigNumber;
        accRewardPerShare: BigNumber;
        totalStaked: BigNumber;
        totalRewards: BigNumber;
      }
    >;

    campaignInfoLen(overrides?: CallOverrides): Promise<BigNumber>;

    "campaignInfoLen()"(overrides?: CallOverrides): Promise<BigNumber>;

    campaignRewardInfo(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        endBlock: BigNumber;
        rewardPerBlock: BigNumber;
      }
    >;

    "campaignRewardInfo(uint256,uint256)"(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        endBlock: BigNumber;
        rewardPerBlock: BigNumber;
      }
    >;

    currentEndBlock(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "currentEndBlock(uint256)"(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    currentRewardPerBlock(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "currentRewardPerBlock(uint256)"(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deposit(
      _campaignID: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "deposit(uint256,uint256)"(
      _campaignID: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    emergencyRewardWithdraw(
      _campaignID: BigNumberish,
      _amount: BigNumberish,
      _beneficiary: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "emergencyRewardWithdraw(uint256,uint256,address)"(
      _campaignID: BigNumberish,
      _amount: BigNumberish,
      _beneficiary: string,
      overrides?: CallOverrides
    ): Promise<void>;

    emergencyWithdraw(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "emergencyWithdraw(uint256)"(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getMultiplier(
      _from: BigNumberish,
      _to: BigNumberish,
      _endBlock: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getMultiplier(uint256,uint256,uint256)"(
      _from: BigNumberish,
      _to: BigNumberish,
      _endBlock: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    harvest(
      _campaignIDs: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "harvest(uint256[])"(
      _campaignIDs: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    initialize(_rewardHolder: string, overrides?: CallOverrides): Promise<void>;

    "initialize(address)"(
      _rewardHolder: string,
      overrides?: CallOverrides
    ): Promise<void>;

    massUpdateCampaigns(overrides?: CallOverrides): Promise<void>;

    "massUpdateCampaigns()"(overrides?: CallOverrides): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    pendingReward(
      _campaignID: BigNumberish,
      _user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "pendingReward(uint256,address)"(
      _campaignID: BigNumberish,
      _user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    rewardHolder(overrides?: CallOverrides): Promise<string>;

    "rewardHolder()"(overrides?: CallOverrides): Promise<string>;

    rewardInfoLen(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "rewardInfoLen(uint256)"(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rewardInfoLimit(overrides?: CallOverrides): Promise<BigNumber>;

    "rewardInfoLimit()"(overrides?: CallOverrides): Promise<BigNumber>;

    setRewardHolder(
      _rewardHolder: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setRewardHolder(address)"(
      _rewardHolder: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setRewardInfoLimit(
      _updatedRewardInfoLimit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setRewardInfoLimit(uint256)"(
      _updatedRewardInfoLimit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateCampaign(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "updateCampaign(uint256)"(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    userInfo(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { amount: BigNumber; rewardDebt: BigNumber }
    >;

    "userInfo(uint256,address)"(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { amount: BigNumber; rewardDebt: BigNumber }
    >;

    withdraw(
      _campaignID: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdraw(uint256,uint256)"(
      _campaignID: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    AddCampaignInfo(
      campaignID: BigNumberish | null,
      stakingToken: null,
      rewardToken: null,
      startBlock: null
    ): EventFilter;

    AddRewardInfo(
      campaignID: BigNumberish | null,
      phase: BigNumberish | null,
      endBlock: null,
      rewardPerBlock: null
    ): EventFilter;

    Deposit(user: string | null, amount: null, campaign: null): EventFilter;

    EmergencyWithdraw(
      user: string | null,
      amount: null,
      campaign: null
    ): EventFilter;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;

    SetRewardHolder(rewardHolder: null): EventFilter;

    SetRewardInfoLimit(rewardInfoLimit: null): EventFilter;

    Withdraw(user: string | null, amount: null, campaign: null): EventFilter;
  };

  estimateGas: {
    addCampaignInfo(
      _stakingToken: string,
      _rewardToken: string,
      _startBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addCampaignInfo(address,address,uint256)"(
      _stakingToken: string,
      _rewardToken: string,
      _startBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    addRewardInfo(
      _campaignID: BigNumberish,
      _endBlock: BigNumberish,
      _rewardPerBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addRewardInfo(uint256,uint256,uint256)"(
      _campaignID: BigNumberish,
      _endBlock: BigNumberish,
      _rewardPerBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    campaignInfo(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "campaignInfo(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    campaignInfoLen(overrides?: CallOverrides): Promise<BigNumber>;

    "campaignInfoLen()"(overrides?: CallOverrides): Promise<BigNumber>;

    campaignRewardInfo(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "campaignRewardInfo(uint256,uint256)"(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    currentEndBlock(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "currentEndBlock(uint256)"(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    currentRewardPerBlock(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "currentRewardPerBlock(uint256)"(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deposit(
      _campaignID: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "deposit(uint256,uint256)"(
      _campaignID: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    emergencyRewardWithdraw(
      _campaignID: BigNumberish,
      _amount: BigNumberish,
      _beneficiary: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "emergencyRewardWithdraw(uint256,uint256,address)"(
      _campaignID: BigNumberish,
      _amount: BigNumberish,
      _beneficiary: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    emergencyWithdraw(
      _campaignID: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "emergencyWithdraw(uint256)"(
      _campaignID: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getMultiplier(
      _from: BigNumberish,
      _to: BigNumberish,
      _endBlock: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getMultiplier(uint256,uint256,uint256)"(
      _from: BigNumberish,
      _to: BigNumberish,
      _endBlock: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    harvest(
      _campaignIDs: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "harvest(uint256[])"(
      _campaignIDs: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    initialize(
      _rewardHolder: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(address)"(
      _rewardHolder: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    massUpdateCampaigns(overrides?: Overrides): Promise<BigNumber>;

    "massUpdateCampaigns()"(overrides?: Overrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    pendingReward(
      _campaignID: BigNumberish,
      _user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "pendingReward(uint256,address)"(
      _campaignID: BigNumberish,
      _user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    rewardHolder(overrides?: CallOverrides): Promise<BigNumber>;

    "rewardHolder()"(overrides?: CallOverrides): Promise<BigNumber>;

    rewardInfoLen(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "rewardInfoLen(uint256)"(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rewardInfoLimit(overrides?: CallOverrides): Promise<BigNumber>;

    "rewardInfoLimit()"(overrides?: CallOverrides): Promise<BigNumber>;

    setRewardHolder(
      _rewardHolder: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setRewardHolder(address)"(
      _rewardHolder: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setRewardInfoLimit(
      _updatedRewardInfoLimit: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setRewardInfoLimit(uint256)"(
      _updatedRewardInfoLimit: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    updateCampaign(
      _campaignID: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "updateCampaign(uint256)"(
      _campaignID: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    userInfo(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "userInfo(uint256,address)"(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdraw(
      _campaignID: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "withdraw(uint256,uint256)"(
      _campaignID: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addCampaignInfo(
      _stakingToken: string,
      _rewardToken: string,
      _startBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addCampaignInfo(address,address,uint256)"(
      _stakingToken: string,
      _rewardToken: string,
      _startBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    addRewardInfo(
      _campaignID: BigNumberish,
      _endBlock: BigNumberish,
      _rewardPerBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addRewardInfo(uint256,uint256,uint256)"(
      _campaignID: BigNumberish,
      _endBlock: BigNumberish,
      _rewardPerBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    campaignInfo(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "campaignInfo(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    campaignInfoLen(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "campaignInfoLen()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    campaignRewardInfo(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "campaignRewardInfo(uint256,uint256)"(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    currentEndBlock(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "currentEndBlock(uint256)"(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    currentRewardPerBlock(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "currentRewardPerBlock(uint256)"(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deposit(
      _campaignID: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "deposit(uint256,uint256)"(
      _campaignID: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    emergencyRewardWithdraw(
      _campaignID: BigNumberish,
      _amount: BigNumberish,
      _beneficiary: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "emergencyRewardWithdraw(uint256,uint256,address)"(
      _campaignID: BigNumberish,
      _amount: BigNumberish,
      _beneficiary: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    emergencyWithdraw(
      _campaignID: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "emergencyWithdraw(uint256)"(
      _campaignID: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getMultiplier(
      _from: BigNumberish,
      _to: BigNumberish,
      _endBlock: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getMultiplier(uint256,uint256,uint256)"(
      _from: BigNumberish,
      _to: BigNumberish,
      _endBlock: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    harvest(
      _campaignIDs: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "harvest(uint256[])"(
      _campaignIDs: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _rewardHolder: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(address)"(
      _rewardHolder: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    massUpdateCampaigns(overrides?: Overrides): Promise<PopulatedTransaction>;

    "massUpdateCampaigns()"(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pendingReward(
      _campaignID: BigNumberish,
      _user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "pendingReward(uint256,address)"(
      _campaignID: BigNumberish,
      _user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    rewardHolder(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "rewardHolder()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rewardInfoLen(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "rewardInfoLen(uint256)"(
      _campaignID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rewardInfoLimit(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "rewardInfoLimit()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setRewardHolder(
      _rewardHolder: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setRewardHolder(address)"(
      _rewardHolder: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setRewardInfoLimit(
      _updatedRewardInfoLimit: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setRewardInfoLimit(uint256)"(
      _updatedRewardInfoLimit: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    updateCampaign(
      _campaignID: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "updateCampaign(uint256)"(
      _campaignID: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    userInfo(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "userInfo(uint256,address)"(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      _campaignID: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "withdraw(uint256,uint256)"(
      _campaignID: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
