/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IMdexSwapMiningInterface extends ethers.utils.Interface {
  functions: {
    "getUserReward(uint256)": FunctionFragment;
    "takerWithdraw()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getUserReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "takerWithdraw",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getUserReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "takerWithdraw",
    data: BytesLike
  ): Result;

  events: {};
}

export class IMdexSwapMining extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IMdexSwapMiningInterface;

  functions: {
    getUserReward(
      pid: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    "getUserReward(uint256)"(
      pid: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    takerWithdraw(overrides?: Overrides): Promise<ContractTransaction>;

    "takerWithdraw()"(overrides?: Overrides): Promise<ContractTransaction>;
  };

  getUserReward(
    pid: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  "getUserReward(uint256)"(
    pid: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  takerWithdraw(overrides?: Overrides): Promise<ContractTransaction>;

  "takerWithdraw()"(overrides?: Overrides): Promise<ContractTransaction>;

  callStatic: {
    getUserReward(
      pid: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    "getUserReward(uint256)"(
      pid: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    takerWithdraw(overrides?: CallOverrides): Promise<void>;

    "takerWithdraw()"(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getUserReward(
      pid: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getUserReward(uint256)"(
      pid: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    takerWithdraw(overrides?: Overrides): Promise<BigNumber>;

    "takerWithdraw()"(overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getUserReward(
      pid: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getUserReward(uint256)"(
      pid: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    takerWithdraw(overrides?: Overrides): Promise<PopulatedTransaction>;

    "takerWithdraw()"(overrides?: Overrides): Promise<PopulatedTransaction>;
  };
}
