"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.grazingRangePools = exports.MarsEcosystemGrazingRangePools = exports.latteSwapGrazingRangePools = exports.scientixGrazingRangePools = exports.alpacaGrazingRangePools = void 0;
const entity_1 = require("../entity");
const tokenProfile_1 = require("./tokenProfile");
const pools_1 = require("../constants/pools");
const view_1 = require("../utils/view");
exports.alpacaGrazingRangePools = view_1.isMainnet()
    ? [
        {
            name: 'ETERNAL',
            rewardToken: tokenProfile_1.mapTokenProfiles['eternal'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://cryptomines.app/',
            campaignId: pools_1.GrazingRangeIbAlpacaETERNALPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GC87ZUUVD3',
        },
        {
            name: 'PLUT',
            rewardToken: tokenProfile_1.mapTokenProfiles['plut'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://plutos.network/',
            campaignId: pools_1.GrazingRangeIbAlpacaPLUTPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GC6eZUU1kb',
        },
        {
            name: 'SPS',
            rewardToken: tokenProfile_1.mapTokenProfiles['sps'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://splinterlands.com/',
            campaignId: pools_1.GrazingRangeIbAlpacaSPSPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCyiZUUdQE',
        },
        {
            name: 'CAPS',
            rewardToken: tokenProfile_1.mapTokenProfiles['caps'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://www.ternoa.com/',
            campaignId: pools_1.GrazingRangeIbAlpacaCAPSPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCZDZUUvwv',
        },
        {
            name: 'TENFI',
            rewardToken: tokenProfile_1.mapTokenProfiles['tenfi'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://ten.finance/',
            campaignId: pools_1.GrazingRangeIbAlpacaTENPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCrMYUURLS',
        },
        {
            name: 'DEP',
            rewardToken: tokenProfile_1.mapTokenProfiles['dep'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://dea.sg/',
            campaignId: pools_1.GrazingRangeIbAlpacaDEPPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GC9yYUU88q',
        },
        {
            name: 'WNOW',
            rewardToken: tokenProfile_1.mapTokenProfiles['wnow'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://walletnow.net/',
            campaignId: pools_1.GrazingRangeIbAlpacaWNOWPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GC4F8UU9vx',
        },
        {
            name: 'LEON',
            rewardToken: tokenProfile_1.mapTokenProfiles['leon'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://www.leonicornswap.com/',
            campaignId: pools_1.GrazingRangeIbAlpacaLEONPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCoT8UUZrt',
        },
        {
            name: 'ARV',
            rewardToken: tokenProfile_1.mapTokenProfiles['arv'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://ariva.digital/',
            campaignId: pools_1.GrazingRangeIbAlpacaARVPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCvM8UUefa',
        },
        {
            name: 'XWIN',
            rewardToken: tokenProfile_1.mapTokenProfiles['xwin'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://xwin.finance/',
            campaignId: pools_1.GrazingRangeIbAlpacaXWINPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCxU8UUSan',
        },
        {
            name: 'SKILL',
            rewardToken: tokenProfile_1.mapTokenProfiles['skill'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://www.cryptoblades.io/',
            campaignId: pools_1.GrazingRangeIbAlpacaSKILLPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCiD6UURfQ',
        },
        {
            name: 'SHEESHA',
            rewardToken: tokenProfile_1.mapTokenProfiles['sheesha'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://www.sheeshafinance.io/',
            campaignId: pools_1.GrazingRangeIbAlpacaSHEESHAPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCy18UUTpt',
        },
        {
            name: 'NFTY',
            rewardToken: tokenProfile_1.mapTokenProfiles['nfty'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://nftylabs.org/',
            campaignId: pools_1.GrazingRangeIbAlpacaNFTYPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCri6UU7aH',
        },
        {
            name: 'BMON',
            rewardToken: tokenProfile_1.mapTokenProfiles['bmon'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://binamon.org/',
            campaignId: pools_1.GrazingRangeIbAlpacaBMONPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCYo8UUd29',
        },
        {
            name: 'MONI',
            rewardToken: tokenProfile_1.mapTokenProfiles['moni'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://monstainfinite.com/',
            campaignId: pools_1.GrazingRangeIbAlpacaMONIPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCHQ6UUEHg',
        },
        {
            name: 'POLAR',
            rewardToken: tokenProfile_1.mapTokenProfiles['polar'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://www.polarsync.app/',
            campaignId: pools_1.GrazingRangeIbAlpacaPOLARPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCaW6UUYgZ',
        },
        {
            name: 'LUCKY',
            rewardToken: tokenProfile_1.mapTokenProfiles['lucky'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://www.luckylion.io/',
            campaignId: pools_1.GrazingRangeIbAlpacaLUCKYPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCFj6UUpUc',
        },
        {
            name: 'POTS',
            rewardToken: tokenProfile_1.mapTokenProfiles['pots'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://moonpot.com/',
            campaignId: pools_1.GrazingRangeIbAlpacaPOTSPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCzwfUURBU',
        },
        {
            name: 'PEAR',
            rewardToken: tokenProfile_1.mapTokenProfiles['pear'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://pearzap.com/',
            campaignId: pools_1.GrazingRangeIbAlpacaPEARPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCvgfUUNMP',
        },
        {
            name: 'QBT',
            rewardToken: tokenProfile_1.mapTokenProfiles['qbt'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://qbt.fi/',
            campaignId: pools_1.GrazingRangeIbAlpacaQBTPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCYrfUUTYk',
        },
        {
            name: 'DVI',
            rewardToken: tokenProfile_1.mapTokenProfiles['dvi'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://dvision.network/',
            campaignId: pools_1.GrazingRangeIbAlpacaDVIPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCCq1UUMVy',
        },
        {
            name: 'NAOS',
            rewardToken: tokenProfile_1.mapTokenProfiles['naos'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://naos.finance/',
            campaignId: pools_1.GrazingRangeIbAlpacaNAOSPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCcLmUUtFk',
        },
        {
            name: 'bMXX',
            rewardToken: tokenProfile_1.mapTokenProfiles['bmxx'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://multiplier.finance/',
            campaignId: pools_1.GrazingRangeIbAlpacabMXX1PoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: '',
        },
        {
            name: 'BELT',
            rewardToken: tokenProfile_1.mapTokenProfiles['belt'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://belt.fi/',
            campaignId: pools_1.GrazingRangeIbAlpacaBELTPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: '',
        },
        {
            name: 'BOR',
            rewardToken: tokenProfile_1.mapTokenProfiles['bor'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://www.boringdao.com/',
            campaignId: pools_1.GrazingRangeIbAlpacaBORPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: '',
        },
        {
            name: 'BRY',
            rewardToken: tokenProfile_1.mapTokenProfiles['bry'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://berrydata.co/#/home/',
            campaignId: pools_1.GrazingRangeIbAlpacaBRYPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: '',
        },
        {
            name: 'pCWS',
            rewardToken: tokenProfile_1.mapTokenProfiles['cws'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://www.seascape.network/',
            campaignId: pools_1.GrazingRangeIbAlpacaCWSPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: '',
        },
        {
            name: 'SWINGBY',
            rewardToken: tokenProfile_1.mapTokenProfiles['swingby'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://swingby.network/',
            campaignId: pools_1.GrazingRangeIbAlpacaSWINGBYPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: '',
        },
        {
            name: 'DODO',
            rewardToken: tokenProfile_1.mapTokenProfiles['dodo'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://dodoex.io/',
            campaignId: pools_1.GrazingRangeIbAlpacaDODOPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: '',
        },
        {
            name: 'ODDZ',
            rewardToken: tokenProfile_1.mapTokenProfiles['oddz'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://oddz.fi/',
            campaignId: pools_1.GrazingRangeIbAlpacaODDZPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: '',
        },
        {
            name: 'FORM',
            rewardToken: tokenProfile_1.mapTokenProfiles['form'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://formation.fi/',
            campaignId: pools_1.GrazingRangeIbAlpacaFORMPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCdZoUUXFU',
        },
        {
            name: 'ORBS',
            rewardToken: tokenProfile_1.mapTokenProfiles['orbs'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://www.orbs.com/',
            campaignId: pools_1.GrazingRangeIbAlpacaORBSPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCKSoUU1z1',
        },
        {
            name: 'WEX',
            rewardToken: tokenProfile_1.mapTokenProfiles['wex'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://wault.finance/',
            campaignId: pools_1.GrazingRangeIbAlpacaWEXPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCMCoUUaFB',
        },
        {
            name: 'PMON',
            rewardToken: tokenProfile_1.mapTokenProfiles['pmon'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://polychainmonsters.com/',
            campaignId: pools_1.GrazingRangeIbAlpacaPMONPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GC891UUwjC',
        },
        {
            name: 'PHA',
            rewardToken: tokenProfile_1.mapTokenProfiles['pha'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://phala.network/en/',
            campaignId: pools_1.GrazingRangeIbAlpacaPHAPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCzX1UU7KZ',
        },
        {
            name: 'ALM',
            rewardToken: tokenProfile_1.mapTokenProfiles['alm'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://alium.finance',
            campaignId: pools_1.GrazingRangeIbAlpacaALMPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GC4q1UUi38',
        },
        {
            name: 'KALA',
            rewardToken: tokenProfile_1.mapTokenProfiles['kala'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://kalata.io/',
            campaignId: pools_1.GrazingRangeIbAlpacaKALAPoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GC3b1UUqaD',
        },
    ]
    : [
        {
            name: 'BUSD',
            rewardToken: tokenProfile_1.mapTokenProfiles['busd'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: '#',
            campaignId: pools_1.GrazingRangeIbAlpacaBUSD1PoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: '',
        },
        {
            name: 'BUSD-2',
            rewardToken: tokenProfile_1.mapTokenProfiles['busd'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: '#',
            campaignId: pools_1.GrazingRangeIbAlpacaBUSD2PoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: '',
        },
        {
            name: 'BUSD-3',
            rewardToken: tokenProfile_1.mapTokenProfiles['busd'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: '#',
            campaignId: pools_1.GrazingRangeIbAlpacaBUSD3PoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: '',
        },
        {
            name: 'BUSD-4',
            rewardToken: tokenProfile_1.mapTokenProfiles['busd'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: '#',
            campaignId: pools_1.GrazingRangeIbAlpacaBUSD4PoolId,
            type: entity_1.GrazingRangeType.AlpacaGrazinRange,
            claimNFTUrl: '',
        },
    ];
exports.scientixGrazingRangePools = view_1.isMainnet()
    ? [
        {
            name: 'SCIX',
            rewardToken: tokenProfile_1.mapTokenProfiles['scix'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://scientix.finance',
            campaignId: pools_1.ScientixStakingPoolsIbAlpacaSCIXPoolId,
            type: entity_1.GrazingRangeType.ScientixStakingPools,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCTy1UURrM',
        },
    ]
    : [
        {
            name: 'SCIX',
            rewardToken: tokenProfile_1.mapTokenProfiles['scix'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://scientix.finance',
            campaignId: pools_1.ScientixStakingPoolsIbAlpacaSCIXPoolId,
            type: entity_1.GrazingRangeType.ScientixStakingPools,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCTy1UURrM',
        },
    ];
exports.latteSwapGrazingRangePools = view_1.isMainnet()
    ? [
        {
            name: 'LATTE',
            rewardToken: tokenProfile_1.mapTokenProfiles['latte'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://www.latteswap.com/',
            campaignId: pools_1.LatteSwapMasterBaristaIbAlpacaLATTEPoolId,
            type: entity_1.GrazingRangeType.LatteSwapMasterBarista,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCkzfUUW5S',
        },
    ]
    : [];
exports.MarsEcosystemGrazingRangePools = view_1.isMainnet()
    ? [
        {
            name: 'MarsEcosystem',
            rewardToken: tokenProfile_1.mapTokenProfiles['xms'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://app.marsecosystem.com/home',
            campaignId: pools_1.MarsEcosystemLiquidityMiningMasterPoolId,
            type: entity_1.GrazingRangeType.MarsEcosystemLiquidityMiningMaster,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCVw8UUXx9',
        },
    ]
    : [
        {
            name: 'MarsEcosystem',
            rewardToken: tokenProfile_1.mapTokenProfiles['xms'],
            stakingToken: tokenProfile_1.mapTokenProfiles['ibALPACA'],
            projectSiteUrl: 'https://app.marsecosystem.com/home',
            campaignId: pools_1.MarsEcosystemLiquidityMiningMasterPoolId,
            type: entity_1.GrazingRangeType.MarsEcosystemLiquidityMiningMaster,
            claimNFTUrl: 'https://galaxy.eco/alpacafinance/campaign/GCVw8UUXx9',
        },
    ];
exports.grazingRangePools = [
    ...exports.scientixGrazingRangePools,
    ...exports.latteSwapGrazingRangePools,
    ...exports.MarsEcosystemGrazingRangePools,
    ...exports.alpacaGrazingRangePools,
];
