import { BigNumber } from '@ethersproject/bignumber';
export declare const NetworkContextName = "NETWORK";
export declare const NativeTokenSlug = "binancecoin";
export declare const GasLimit: BigNumber;
export declare const OpenPositionGasLimit: BigNumber;
export declare const ClosePositionGasLimit: BigNumber;
export declare const BlockConfirmation = 1;
export declare const MinimumLiquidity: BigNumber;
export declare const MaxPercentage: BigNumber;
export declare const BnBDecimalPoint = 18;
export declare const SlippageMaxPercent: BigNumber;
export declare const BlockTime: BigNumber;
export declare const BlockNumberPerYear: BigNumber;
export declare const BasisPoint: BigNumber;
export declare const YearInDay = 365;
export declare const WEEK_IN_YEAR = 52;
export declare const SECONDS_IN_WEEK: number;
export declare const config: import("./config").IConfig;
export declare const ChainId: number;
export declare const LpPoolBuybackBps: BigNumber;
export declare const LpPoolTreasuryBps: BigNumber;
export declare const LpPoolPerformanceFeeBps: BigNumber;
export declare const SaPoolBuybackBps: BigNumber;
export declare const SaPoolTreasuryBps: BigNumber;
export declare const SaPoolPerformanceFeeBps: BigNumber;
export declare const InverseLpPoolBuybackBps: BigNumber;
export declare const InverseLpPoolTreasuryBps: BigNumber;
export declare const InverseLpPoolPerformanceFeeBps: BigNumber;
export declare const InverseSaPoolBuybackBps: BigNumber;
export declare const InverseSaTreasuryBps: BigNumber;
export declare const InverseSaPerformanceFeeBps: BigNumber;
export declare const fdALPACAPoolAllocPoint = 300;
