"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.availableLendingPools = void 0;
const contracts_1 = require("./contracts");
const fiatPrice_1 = require("../utils/fiatPrice");
const stakingPool_1 = require("./stakingPool");
exports.availableLendingPools = [
    {
        tokenName: 'ALPACA',
        tokenUnit: 'ALPACA',
        tokenIconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/alpaca.svg',
        tokenAddress: contracts_1.AlpacaTokenAddress,
        isTokenNative: false,
        isNew: false,
        ibName: 'ibALPACA',
        ibUnit: 'ibALPACA',
        ibVaultAddress: contracts_1.ALPACAVaultAddress,
        ibIconUrl: '',
        associatedStakingPool: stakingPool_1.availableStakePools.find((o) => o.name === 'ibALPACA'),
        getPriceInUSD: () => fiatPrice_1.getAlpacaPrice(),
    },
    {
        tokenName: 'BNB',
        tokenUnit: 'BNB',
        tokenIconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/bnb.svg',
        tokenAddress: contracts_1.WBNBAddress,
        isTokenNative: true,
        isNew: false,
        ibName: 'ibWBNB',
        ibUnit: 'ibBNB',
        ibVaultAddress: contracts_1.BNBVaultAddress,
        ibIconUrl: '',
        associatedStakingPool: stakingPool_1.availableStakePools.find((o) => o.name === 'ibBNB'),
        getPriceInUSD: () => fiatPrice_1.getTokenPrice('wbnb'),
    },
    {
        tokenName: 'BUSD',
        tokenUnit: 'BUSD',
        tokenIconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/busd.svg',
        tokenAddress: contracts_1.BUSDAddress,
        isTokenNative: false,
        isNew: false,
        ibName: 'ibBUSD',
        ibUnit: 'ibBUSD',
        ibVaultAddress: contracts_1.BUSDVaultAddress,
        ibIconUrl: '',
        associatedStakingPool: stakingPool_1.availableStakePools.find((o) => o.name === 'ibBUSD'),
        getPriceInUSD: () => fiatPrice_1.getTokenPrice('binance-usd'),
    },
    {
        tokenName: 'USDT',
        tokenUnit: 'USDT',
        tokenIconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/usdt.svg',
        tokenAddress: contracts_1.USDTAddress,
        isTokenNative: false,
        isNew: false,
        ibName: 'ibUSDT',
        ibUnit: 'ibUSDT',
        ibVaultAddress: contracts_1.USDTVaultAddress,
        ibIconUrl: '',
        associatedStakingPool: stakingPool_1.availableStakePools.find((o) => o.name === 'ibUSDT'),
        getPriceInUSD: () => fiatPrice_1.getTokenPrice('tether'),
    },
    {
        tokenName: 'USDC',
        tokenUnit: 'USDC',
        tokenIconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/usdc.svg',
        tokenAddress: contracts_1.USDCAddress,
        isTokenNative: false,
        isNew: false,
        ibName: 'ibUSDC',
        ibUnit: 'ibUSDC',
        ibVaultAddress: contracts_1.USDCVaultAddress,
        ibIconUrl: '',
        associatedStakingPool: stakingPool_1.availableStakePools.find((o) => o.name === 'ibUSDC'),
        getPriceInUSD: () => fiatPrice_1.getTokenPrice('usd-coin'),
    },
    {
        tokenName: 'TUSD',
        tokenUnit: 'TUSD',
        tokenIconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/tusd.svg',
        tokenAddress: contracts_1.TUSDAddress,
        isTokenNative: false,
        isNew: false,
        ibName: 'ibTUSD',
        ibUnit: 'ibTUSD',
        ibVaultAddress: contracts_1.TUSDVaultAddress,
        ibIconUrl: '',
        associatedStakingPool: stakingPool_1.availableStakePools.find((o) => o.name === 'ibTUSD'),
        getPriceInUSD: () => fiatPrice_1.getTokenPrice('true-usd'),
    },
    {
        tokenName: 'BTCB',
        tokenUnit: 'BTCB',
        tokenIconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/btcb.svg',
        tokenAddress: contracts_1.BTCBAddress,
        isTokenNative: false,
        isNew: false,
        ibName: 'ibBTCB',
        ibUnit: 'ibBTCB',
        ibVaultAddress: contracts_1.BTCBVaultAddress,
        ibIconUrl: '',
        associatedStakingPool: stakingPool_1.availableStakePools.find((o) => o.name === 'ibBTCB'),
        getPriceInUSD: () => fiatPrice_1.getTokenPrice('bitcoin-bep2'),
    },
    {
        tokenName: 'ETH',
        tokenUnit: 'ETH',
        tokenIconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/eth.svg',
        tokenAddress: contracts_1.ETHAddress,
        isTokenNative: false,
        isNew: false,
        ibName: 'ibETH',
        ibUnit: 'ibETH',
        ibVaultAddress: contracts_1.ETHVaultAddress,
        ibIconUrl: '',
        associatedStakingPool: stakingPool_1.availableStakePools.find((o) => o.name === 'ibETH'),
        getPriceInUSD: () => fiatPrice_1.getTokenPrice('ethereum'),
    },
];
