"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getDisplaySymbol = exports.getTokenAddress = exports.getLpTokenAddress = exports.mapLpTokenProfiles = exports.lpTokenProfiles = exports.mapAddressTokenProfiles = exports.mapTokenProfiles = exports.tokenProfiles = void 0;
const contracts_1 = require("./contracts");
const entity_1 = require("../entity");
const fiatPrice_1 = require("../utils/fiatPrice");
const entity_2 = require("../entity");
const ausdContracts_1 = require("./ausdContracts");
const busdToken = {
    name: 'Binance USD',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.BUSD,
    displaySymbol: 'BUSD',
    slug: 'binance-usd',
    address: contracts_1.BUSDAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/busd.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0xe9e7cea3dedca5984780bafc599bd69add087d56',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('binance-usd'),
    priceSourceIds: {
        coinMarketCap: 4687,
        coinGecko: 'binance-usd',
        cryptoCompare: entity_2.TokenSymbol.BUSD,
    },
};
const bnbToken = {
    name: 'Wrapped BNB',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.WBNB,
    displaySymbol: 'BNB',
    slug: 'binancecoin',
    address: contracts_1.WBNBAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/bnb.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c',
    decimal: 18,
    isTokenNative: true,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('binancecoin'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 1839,
        coinGecko: 'binancecoin',
        cryptoCompare: entity_2.TokenSymbol.WBNB,
    },
};
const ethToken = {
    name: 'Ethereum',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.ETH,
    displaySymbol: 'ETH',
    slug: 'ethereum',
    address: contracts_1.ETHAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/eth.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x2170ed0880ac9a755fd29b2688956bd959f933f8',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('ethereum'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.ETH, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.ETH, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 1027,
        coinGecko: 'ethereum',
        cryptoCompare: entity_2.TokenSymbol.ETH,
    },
};
const btcbToken = {
    name: 'Bitcoin BEP2',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.BTCB,
    displaySymbol: 'BTCB',
    slug: 'bitcoin-bep2',
    address: contracts_1.BTCBAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/btcb.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('bitcoin-bep2'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.BTCB, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.BTCB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 4023,
        coinGecko: 'bitcoin-bep2',
        cryptoCompare: entity_2.TokenSymbol.BTCB,
    },
};
const cakeToken = {
    name: 'PancakeSwap',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.CAKE,
    displaySymbol: 'CAKE',
    slug: 'pancakeswap-token',
    address: contracts_1.CAKEAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/cake.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('pancakeswap-token'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.CAKE, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.CAKE, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 7186,
        coinGecko: 'pancakeswap-token',
        cryptoCompare: entity_2.TokenSymbol.CAKE,
    },
};
const usdtToken = {
    name: 'Tether',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.USDT,
    displaySymbol: 'USDT',
    slug: 'tether',
    address: contracts_1.USDTAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/usdt.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x55d398326f99059ff775485246999027b3197955',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('tether'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.USDT, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.USDT, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 825,
        coinGecko: 'tether',
        cryptoCompare: entity_2.TokenSymbol.USDT,
    },
};
const dotToken = {
    name: 'Polkadot',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.DOT,
    displaySymbol: 'DOT',
    slug: 'polkadot',
    address: contracts_1.DOTAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/dot.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x7083609fce4d1d8dc0c979aab8c869ea2c873402',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('polkadot'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.DOT, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.DOT, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 6636,
        coinGecko: 'polkadot',
        cryptoCompare: entity_2.TokenSymbol.DOT,
    },
};
const uniToken = {
    name: 'Uniswap',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.UNI,
    displaySymbol: 'UNI',
    slug: 'uniswap',
    address: contracts_1.UNIAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/uni.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0xbf5140a22578168fd562dccf235e5d43a02ce9b1',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('uniswap'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.UNI, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.UNI, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 7083,
        coinGecko: 'uniswap',
        cryptoCompare: entity_2.TokenSymbol.UNI,
    },
};
const linkToken = {
    name: 'Chainlink',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.LINK,
    displaySymbol: 'LINK',
    slug: 'chainlink',
    address: contracts_1.LINKAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/link.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0xf8a0bf9cf54bb92f17374d9e9a321e6a111a51bd',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('chainlink'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.LINK, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.LINK, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 1975,
        coinGecko: 'chainlink',
        cryptoCompare: entity_2.TokenSymbol.LINK,
    },
};
const xvsToken = {
    name: 'Venus',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.XVS,
    displaySymbol: 'XVS',
    slug: 'venus',
    address: contracts_1.XVSAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/xvs.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0xcf6bb5389c92bdda8a3747ddb454cb7a64626c63',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('venus'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.XVS, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.XVS, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 7288,
        coinGecko: 'venus',
        cryptoCompare: entity_2.TokenSymbol.XVS,
    },
};
const yfiToken = {
    name: 'Yearn.finance',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.YFI,
    displaySymbol: 'YFI',
    slug: 'yearn-finance',
    address: contracts_1.YFIAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/yfi.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('yearn-finance'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.YFI, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.YFI, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 5864,
        coinGecko: 'yearn-finance',
        cryptoCompare: entity_2.TokenSymbol.YFI,
    },
};
const vaiToken = {
    name: 'Vai',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.VAI,
    displaySymbol: 'VAI',
    slug: 'vai',
    address: contracts_1.VAIAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/vai.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x4bd17003473389a42daf6a0a729f6fdb328bbbd7',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('vai'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.VAI, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.VAI, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 7824,
        coinGecko: 'vai',
        cryptoCompare: entity_2.TokenSymbol.VAI,
    },
};
const usdcToken = {
    name: 'USD Coin',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.USDC,
    displaySymbol: 'USDC',
    slug: 'usd-coin',
    address: contracts_1.USDCAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/usdc.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('usd-coin'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.USDC, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.USDC, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 3408,
        coinGecko: 'usd-coin',
        cryptoCompare: entity_2.TokenSymbol.USDC,
    },
};
const daiToken = {
    name: 'Dai',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.DAI,
    displaySymbol: 'DAI',
    slug: 'dai',
    address: contracts_1.DAIAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/dai.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x1af3f329e8be154074d8769d1ffa4ee058b1dbc3',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('dai'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.DAI, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.DAI, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 4943,
        coinGecko: 'dai',
        cryptoCompare: entity_2.TokenSymbol.DAI,
    },
};
const ustToken = {
    name: 'TerraUSD',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.UST,
    displaySymbol: 'UST',
    slug: 'terrausd',
    address: contracts_1.USTAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/ust.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x55d398326f99059ff775485246999027b3197955',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('terrausd'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.UST, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.UST, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 7129,
        coinGecko: 'terrausd',
        cryptoCompare: entity_2.TokenSymbol.UST,
    },
};
const itamToken = {
    name: 'Itam',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.ITAM,
    displaySymbol: 'ITAM',
    slug: 'itam-games',
    address: contracts_1.ITAMAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/itam.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('itam-games'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.ITAM, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.ITAM, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 6490,
        coinGecko: 'itam-games',
        cryptoCompare: entity_2.TokenSymbol.ITAM,
    },
};
const bethToken = {
    name: 'Binance Eth',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.BETH,
    displaySymbol: 'BETH',
    slug: 'binance-eth',
    address: contracts_1.BETHAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/beth.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('binance-eth'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.BETH, entity_2.TokenSymbol.ETH, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.BETH, entity_2.TokenSymbol.ETH, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 8353,
        coinGecko: 'binance-eth',
        cryptoCompare: entity_2.TokenSymbol.BETH,
    },
};
const compToken = {
    name: 'Compound Governance Token',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.COMP,
    displaySymbol: 'COMP',
    slug: 'compound-governance-token',
    address: contracts_1.COMPAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/comp.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x52ce071bd9b1c4b00a0b92d298c512478cad67e8',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('compound-governance-token'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.COMP, entity_2.TokenSymbol.ETH, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.COMP, entity_2.TokenSymbol.ETH, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 5692,
        coinGecko: 'compound-governance-token',
        cryptoCompare: entity_2.TokenSymbol.COMP,
    },
};
const sushiToken = {
    name: 'Sushi',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.SUSHI,
    displaySymbol: 'SUSHI',
    slug: 'sushi',
    address: contracts_1.SUSHIAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/sushi.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x947950bcc74888a40ffa2593c5798f11fc9124c4',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('sushi'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.SUSHI, entity_2.TokenSymbol.ETH, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.SUSHI, entity_2.TokenSymbol.ETH, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 6758,
        coinGecko: 'sushi',
        cryptoCompare: entity_2.TokenSymbol.SUSHI,
    },
};
const alpacaToken = {
    name: 'Alpaca',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.ALPACA,
    displaySymbol: 'ALPACA',
    slug: 'alpaca-finance',
    address: contracts_1.AlpacaTokenAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/alpaca.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x8f0528ce5ef7b51152a59745befdd91d97091d2f',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('alpaca-finance'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.ALPACA, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.ALPACA, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 8707,
        coinGecko: 'alpaca-finance',
        cryptoCompare: entity_2.TokenSymbol.ALPACA,
    },
};
const bmxxToken = {
    name: 'bmxx',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.BMXX,
    displaySymbol: 'bMXX',
    slug: 'multiplier-bsc',
    address: contracts_1.BMXXAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/bmxx.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('multiplier-bsc'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.BMXX, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.BMXX, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 8618,
        coinGecko: 'multiplier-bsc',
        cryptoCompare: entity_2.TokenSymbol.BMXX,
    },
};
const beltToken = {
    name: 'belt',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.BELT,
    displaySymbol: 'BELT',
    slug: 'belt',
    address: contracts_1.BELTAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/belt.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0xe0e514c71282b6f4e823703a39374cf58dc3ea4f',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('belt'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.BELT, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.BELT, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 8730,
        coinGecko: 'belt',
        cryptoCompare: entity_2.TokenSymbol.BELT,
    },
};
const borToken = {
    name: 'bor',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.BOR,
    displaySymbol: 'BOR',
    slug: 'boringdao',
    address: contracts_1.BORAddress,
    iconUrl: 'https://assets.coingecko.com/coins/images/12917/small/bor_logo.png?1603607502',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('boringdao'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.BOR, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.BOR, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 7509,
        coinGecko: 'boringdao',
        cryptoCompare: entity_2.TokenSymbol.BOR,
    },
};
const bryToken = {
    name: 'bry',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.BRY,
    displaySymbol: 'BRY',
    slug: 'berry-data',
    address: contracts_1.BRYAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/berry.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0xf859Bf77cBe8699013d6Dbc7C2b926Aaf307F830',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('berry-data'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.BRY, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.BRY, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 8483,
        coinGecko: 'berry-data',
        cryptoCompare: entity_2.TokenSymbol.BRY,
    },
};
const pcwsToken = {
    name: 'crowns',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.PCWS,
    displaySymbol: 'pCWS',
    slug: 'crowns',
    address: contracts_1.PCWSAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/cws.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0xbcf39f0edda668c58371e519af37ca705f2bfcbd',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('crowns'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.PCWS, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.PCWS, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 8365,
        coinGecko: 'crowns',
        cryptoCompare: entity_2.TokenSymbol.PCWS,
    },
};
const swingbyToken = {
    name: 'Swingby',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.SWINGBY,
    displaySymbol: 'SWINGBY',
    slug: 'swingby',
    address: contracts_1.SWINGBYAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/swingby.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('swingby'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.SWINGBY, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.SWINGBY, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 5922,
        coinGecko: 'swingby',
        cryptoCompare: entity_2.TokenSymbol.SWINGBY,
    },
};
const dodoToken = {
    name: 'DODO',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.DODO,
    displaySymbol: 'DODO',
    slug: 'dodo',
    address: contracts_1.DODOAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/dodo.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x67ee3cb086f8a16f34bee3ca72fad36f7db929e2',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('dodo'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.DODO, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.DODO, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 7224,
        coinGecko: 'dodo',
        cryptoCompare: entity_2.TokenSymbol.DODO,
    },
};
const sAlpacaToken = {
    name: 'sAlpaca',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.SALPACA,
    displaySymbol: 'sALPACA',
    slug: '',
    address: contracts_1.StronkAlpacaAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/s-alpaca.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: fiatPrice_1.getZero,
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.SALPACA, entity_2.TokenSymbol.ALPACA, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.SALPACA, entity_2.TokenSymbol.ALPACA, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {},
};
const wexToken = {
    name: 'WaultSwap',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.WEX,
    displaySymbol: 'WEX',
    slug: 'waultswap',
    address: contracts_1.WEXAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/wex.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('waultswap'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.WEX, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.WEX, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 9951,
        coinGecko: 'waultswap',
        cryptoCompare: entity_2.TokenSymbol.WEX,
    },
};
const waultxToken = {
    name: 'Wault',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.WAULTX,
    displaySymbol: 'WAULTx',
    slug: 'wault',
    address: contracts_1.WAULTXAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/waultx.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('wault'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.WAULTX, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.WAULTX, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 9478,
        coinGecko: 'wault',
        cryptoCompare: entity_2.TokenSymbol.WAULTX,
    },
};
const oddzToken = {
    name: 'Oddz',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.ODDZ,
    displaySymbol: 'ODDZ',
    slug: 'oddz',
    address: contracts_1.ODDZAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/oddz.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0xcd40f2670cf58720b694968698a5514e924f742d',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('oddz'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.ODDZ, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.ODDZ, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 8717,
        coinGecko: 'oddz',
        cryptoCompare: entity_2.TokenSymbol.ODDZ,
    },
};
const adaToken = {
    name: 'Ada',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.ADA,
    displaySymbol: 'ADA',
    slug: 'cardano',
    address: contracts_1.ADAAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/ada.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x3ee2200efb3400fabb9aacf31297cbdd1d435d47',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('cardano'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.ADA, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.ADA, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 2010,
        coinGecko: 'cardano',
        cryptoCompare: entity_2.TokenSymbol.ADA,
    },
};
const formToken = {
    name: 'Form',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.FORM,
    displaySymbol: 'FORM',
    slug: 'formation-fi',
    address: contracts_1.FORMAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/form-fi.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x25a528af62e56512a19ce8c3cab427807c28cc19',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('formation-fi'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.FORM, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.FORM, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 10408,
        coinGecko: 'formation-fi',
        cryptoCompare: entity_2.TokenSymbol.FORM,
    },
};
const maticToken = {
    name: 'Matic',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.MATIC,
    displaySymbol: 'MATIC',
    slug: 'matic-network',
    address: contracts_1.MATICAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/matic.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('matic-network'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.MATIC, entity_2.TokenSymbol.USDT, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.MATIC, entity_2.TokenSymbol.USDT, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 3890,
        coinGecko: 'matic-network',
        cryptoCompare: entity_2.TokenSymbol.MATIC,
    },
};
const tusdToken = {
    name: 'TrueUSD',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.TUSD,
    displaySymbol: 'TUSD',
    slug: 'true-usd',
    address: contracts_1.TUSDAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/tusd.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x14016e85a25aeb13065688cafb43044c2ef86784',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('true-usd'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.TUSD, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.TUSD, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 2563,
        coinGecko: 'true-usd',
        cryptoCompare: entity_2.TokenSymbol.TUSD,
    },
};
const trxToken = {
    name: 'Tron',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.TRX,
    displaySymbol: 'TRX',
    slug: 'tron',
    address: contracts_1.TRXAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/trx.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x85eac5ac2f758618dfa09bdbe0cf174e7d574d5b',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('tron'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.TRX, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.TRX, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 1958,
        coinGecko: 'tron',
        cryptoCompare: entity_2.TokenSymbol.TRX,
    },
};
const bttToken = {
    name: 'BitTorrent',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.BTT,
    displaySymbol: 'BTT',
    slug: 'bittorrent-old',
    address: contracts_1.BTTAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/btt.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x8595f9da7b868b1822194faed312235e43007b49',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('bittorrent-old'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.BTT, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.BTT, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 3718,
        coinGecko: 'bittorrent-old',
        cryptoCompare: entity_2.TokenSymbol.BTT,
    },
};
const pmonToken = {
    name: 'PolyChainMonsters',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.PMON,
    displaySymbol: 'PMON',
    slug: 'polychain-monsters',
    address: contracts_1.PMONAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/pmon.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x1796ae0b0fa4862485106a0de9b654efe301d0b2',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('polychain-monsters'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.PMON, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.PMON, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 8968,
        coinGecko: 'polychain-monsters',
        cryptoCompare: entity_2.TokenSymbol.PMON,
    },
};
const orbsToken = {
    name: 'Orbs',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.ORBS,
    displaySymbol: 'ORBS',
    slug: 'orbs',
    address: contracts_1.ORBSAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/orbs.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0xebd49b26169e1b52c04cfd19fcf289405df55f80',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('orbs'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.ORBS, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.ORBS, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 3835,
        coinGecko: 'orbs',
        cryptoCompare: entity_2.TokenSymbol.ORBS,
    },
};
const axsToken = {
    name: 'Axie Infinity',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.AXS,
    displaySymbol: 'AXS',
    slug: 'axie-infinity',
    address: contracts_1.AXSAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/axs.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x715d400f88c167884bbcc41c5fea407ed4d2f8a0',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('axie-infinity'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.AXS, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.AXS, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 6783,
        coinGecko: 'axie-infinity',
        cryptoCompare: entity_2.TokenSymbol.AXS,
    },
};
const wusdToken = {
    name: 'Wault USD',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.WUSD,
    displaySymbol: 'WUSD',
    slug: 'wault-usd',
    address: contracts_1.WUSDAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/wusd.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('wault-usd'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromWsRoute([entity_2.TokenSymbol.WUSD, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 11559,
        coinGecko: 'wault-usd',
        cryptoCompare: entity_2.TokenSymbol.WUSD,
    },
};
const phaToken = {
    name: 'Phala Network',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.PHA,
    displaySymbol: 'PHA',
    slug: 'pha',
    address: contracts_1.PHAAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/pha.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x0112e557d400474717056c4e6d40edd846f38351',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('pha'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.PHA, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.PHA, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 6841,
        coinGecko: 'pha',
        cryptoCompare: entity_2.TokenSymbol.PHA,
    },
};
const scixToken = {
    name: 'Scientix',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.SCIX,
    displaySymbol: 'SCIX',
    slug: 'scientix',
    address: contracts_1.SCIXAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/scix.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('scientix'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.SCIX, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 11784,
        coinGecko: 'scientix',
        cryptoCompare: entity_2.TokenSymbol.SCIX,
    },
};
const almToken = {
    name: 'Alium Swap',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.ALM,
    displaySymbol: 'ALM',
    slug: 'alium-swap',
    address: contracts_1.ALMAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/alm.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('alium-swap'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.ALM, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.ALM, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 10428,
        coinGecko: 'alium-swap',
        cryptoCompare: entity_2.TokenSymbol.ALM,
    },
};
const kalaToken = {
    name: 'Kalata Protocol',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.KALA,
    displaySymbol: 'KALA',
    slug: 'kalata',
    address: contracts_1.KALAAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/kala.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('kalata'),
    priceRoutes: [
        entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.KALA, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
        entity_2.ILPRouteV2Factory.createILPFromPcsV1Route([entity_2.TokenSymbol.KALA, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD]),
    ],
    priceSourceIds: {
        coinMarketCap: 9353,
        coinGecko: 'kalata',
        cryptoCompare: entity_2.TokenSymbol.KALA,
    },
};
const mboxToken = {
    name: 'Mobox',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.MBOX,
    displaySymbol: 'MBOX',
    slug: 'mobox',
    address: contracts_1.MBOXAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/mbox.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x3203c9e46ca618c8c1ce5dc67e7e9d75f5da2377',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('mobox'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.MBOX, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 9175,
        coinGecko: 'mobox',
        cryptoCompare: entity_2.TokenSymbol.MBOX,
    },
};
const naosToken = {
    name: 'NAOS Finance',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.NAOS,
    displaySymbol: 'NAOS',
    slug: 'naos-finance',
    address: contracts_1.NAOSAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/naos.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x758d08864fb6cce3062667225ca10b8f00496cc2',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('naos-finance'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.NAOS, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 9504,
        coinGecko: 'naos-finance',
        cryptoCompare: entity_2.TokenSymbol.NAOS,
    },
};
const mdxToken = {
    name: 'Mdex',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.MDX,
    displaySymbol: 'MDX',
    slug: 'mdex',
    address: contracts_1.MDEXAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/mdex.svg',
    buyUrl: 'https://ht.mdex.me/#/swap?outputCurrency=0x25d2e80cb6b86881fd7e07dd263fb79f4abe033c',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('mdex'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromMdxRoute([entity_2.TokenSymbol.MDX, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 8335,
        coinGecko: 'mdex',
        cryptoCompare: entity_2.TokenSymbol.MDX,
    },
};
const dviToken = {
    name: 'Dvision Network',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.DVI,
    displaySymbol: 'DVI',
    slug: 'dvision-network',
    address: contracts_1.DVIAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/dvi.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x758fb037a375f17c7e195cc634d77da4f554255b',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('dvision-network'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.DVI, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 7590,
        coinGecko: 'dvision-network',
        cryptoCompare: entity_2.TokenSymbol.DVI,
    },
};
const latteToken = {
    name: 'LatteSwap',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.LATTE,
    displaySymbol: 'LATTE',
    slug: 'latteswap',
    address: contracts_1.LATTEAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/latte-v2.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: fiatPrice_1.getZero,
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.LATTE, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {},
};
const qbtToken = {
    name: 'Qubit',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.QBT,
    displaySymbol: 'QBT',
    slug: 'qubit',
    address: contracts_1.QBTAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/qbt.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x17b7163cf1dbd286e262ddc68b553d899b93f526',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('qubit'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.QBT, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 11414,
        coinGecko: 'qubit',
        // no cryptoCompare because duplicated with Qbao
    },
};
const pearToken = {
    name: 'Pear',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.PEAR,
    displaySymbol: 'PEAR',
    slug: 'pear',
    address: contracts_1.PEARAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/pear.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('pear'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromAsRoute([entity_2.TokenSymbol.PEAR, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 11105,
        coinGecko: 'pear',
        // no cryptoCompare because duplicated with Qbao
    },
};
const potsToken = {
    name: 'Moonpot',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.POTS,
    displaySymbol: 'POTS',
    slug: 'moonpot',
    address: contracts_1.POTSAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/pots.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x3fcca8648651e5b974dd6d3e50f61567779772a8',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('moonpot'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.POTS, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 11242,
        coinGecko: 'moonpot',
        // not listed on cryptoCompare
    },
};
const luckyToken = {
    name: 'Lucky Lion',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.LUCKY,
    displaySymbol: 'LUCKY',
    slug: 'lucky-lion',
    address: contracts_1.LUCKYAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/lucky.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('lucky-lion'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.LUCKY, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 12233,
        coinGecko: 'lucky-lion',
        // not listed on cryptoCompare
    },
};
const polarToken = {
    name: 'Polar Sync',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.POLAR,
    displaySymbol: 'POLAR',
    slug: 'polar-sync',
    address: contracts_1.POLARAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/polar.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('polar-sync'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.POLAR, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 11540,
        coinGecko: 'polar-sync',
        // not listed on cryptoCompare
    },
};
const moniToken = {
    name: 'Monsta Infinite',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.MONI,
    displaySymbol: 'MONI',
    slug: 'monsta-infinite',
    address: contracts_1.MONIAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/moni.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('monsta-infinite'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.MONI, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 11925,
        coinGecko: 'monsta-infinite',
        cryptoCompare: entity_2.TokenSymbol.MONI,
    },
};
const bmonToken = {
    name: 'Binamon',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.BMON,
    displaySymbol: 'BMON',
    slug: 'binamon',
    address: contracts_1.BMONAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/bmon.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x08ba0619b1e7a582e0bce5bbe9843322c954c340',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('binamon'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.BMON, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 10704,
        coinGecko: 'binamon',
        cryptoCompare: entity_2.TokenSymbol.BMON,
    },
};
const nftyToken = {
    name: 'NFTY Token',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.NFTY,
    displaySymbol: 'NFTY',
    slug: 'nfty-token',
    address: contracts_1.NFTYAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/nfty.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('nfty-token'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromAsRoute([entity_2.TokenSymbol.NFTY, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 12506,
        coinGecko: 'nfty-token',
        // not listed on cryptoCompare
    },
};
const sheeshaToken = {
    name: 'Sheesha Finance',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.SHEESHA,
    displaySymbol: 'SHEESHA',
    slug: 'sheesha-finance-bep20',
    address: contracts_1.SHEESHAAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/sheesha.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('sheesha-finance-bep20'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.SHEESHA, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 10337,
        // not listed on coinGecko
        cryptoCompare: entity_2.TokenSymbol.SHEESHA,
    },
};
const skillToken = {
    name: 'Crypto Blades',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.SKILL,
    displaySymbol: 'SKILL',
    slug: 'cryptoblades',
    address: contracts_1.SKILLAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/skill.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('cryptoblades'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.SKILL, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 9654,
        coinGecko: 'cryptoblades',
        cryptoCompare: entity_2.TokenSymbol.SKILL,
    },
};
const arvToken = {
    name: 'Ariva',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.ARV,
    displaySymbol: 'ARV',
    slug: 'ariva',
    address: contracts_1.ARVAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/arv.svg',
    buyUrl: undefined,
    decimal: 8,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('ariva'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.ARV, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 11541,
        coinGecko: 'ariva',
        // not listed on cryptoCompare
    },
};
const xwinToken = {
    name: 'xWIN Finance',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.XWIN,
    displaySymbol: 'XWIN',
    slug: 'xwin-finance',
    address: contracts_1.XWINAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/xwin.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('xwin-finance'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.XWIN, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 9870,
        coinGecko: 'xwin-finance',
        cryptoCompare: entity_2.TokenSymbol.XWIN,
    },
};
const xmsToken = {
    name: 'Mars Ecosystem',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.XMS,
    displaySymbol: 'XMS',
    slug: 'mars-ecosystem-token',
    address: contracts_1.XMSAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/xms.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('mars-ecosystem-token'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.XMS, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 10030,
        coinGecko: 'mars-ecosystem-token',
        cryptoCompare: entity_2.TokenSymbol.XMS,
    },
};
const leonToken = {
    name: 'Leon Token',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.LEON,
    displaySymbol: 'LEON',
    slug: 'leon-token',
    address: contracts_1.LEONAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/leon.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('leon-token'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.LEON, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 13778,
        // not listed on coinGecko
        // not listed on cryptoCompare
    },
};
const wnowToken = {
    name: 'WalletNow',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.WNOW,
    displaySymbol: 'WNOW',
    slug: 'walletnow',
    address: contracts_1.WNOWAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/wnow.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('walletnow'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.WNOW, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 14257,
        coinGecko: 'walletnow',
        // not listed on cryptoCompare
    },
};
const depToken = {
    name: 'DEAPCOIN',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.DEP,
    displaySymbol: 'DEP',
    slug: 'deapcoin',
    address: contracts_1.DEPAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/dep.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('deapcoin'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromAsRoute([entity_2.TokenSymbol.DEP, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 5429,
        coinGecko: 'deapcoin',
        cryptoCompare: entity_2.TokenSymbol.DEP,
    },
};
const tenfiToken = {
    name: 'TEN',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.TENFI,
    displaySymbol: 'TENFI',
    slug: 'ten',
    address: contracts_1.TENFIAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/tenfi.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('ten'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.TENFI, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 10031,
        coinGecko: 'ten',
        cryptoCompare: entity_2.TokenSymbol.TENFI,
    },
};
const capsToken = {
    name: 'Ternoa',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.CAPS,
    displaySymbol: 'CAPS',
    slug: 'ternoa',
    address: contracts_1.CAPSAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/caps.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('ternoa'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.CAPS, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 9291,
        coinGecko: 'ternoa',
    },
};
const spsToken = {
    name: 'Splinterlands',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.SPS,
    displaySymbol: 'SPS',
    slug: 'splinterlands',
    address: contracts_1.SPSAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/sps.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x1633b7157e7638c4d6593436111bf125ee74703f',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('splinterlands'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.SPS, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 11035,
        coinGecko: 'splinterlands',
        cryptoCompare: entity_2.TokenSymbol.SPS,
    },
};
const plutToken = {
    name: 'Plutos Network',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.PLUT,
    displaySymbol: 'PLUT',
    slug: 'plutos-network',
    address: contracts_1.PLUTAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/plut.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('plutos-network'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.PLUT, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 10525,
        coinGecko: 'plutos-network',
        // not listed on cryptoCompare
    },
};
const eternalToken = {
    name: 'CryptoMines Eternal',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.ETERNAL,
    displaySymbol: 'ETERNAL',
    slug: 'cryptomines-eternal',
    address: contracts_1.ETERNALAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/eternal.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('cryptomines-eternal'),
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.ETERNAL, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD])],
    priceSourceIds: {
        coinMarketCap: 11736,
        coinGecko: 'cryptomines-eternal',
        // not listed on cryptoCompare
    },
};
const thgToken = {
    name: 'Thetan Gem',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.THG,
    displaySymbol: 'THG',
    slug: 'thetan-arena',
    address: contracts_1.THGAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/thg.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x9fd87aefe02441b123c3c32466cd9db4c578618f',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('thetan-arena'),
    priceSourceIds: {
        coinMarketCap: 11926,
        coinGecko: 'thetan-arena',
        cryptoCompare: entity_2.TokenSymbol.THG,
    },
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.THG, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD])],
};
const paybSwapToken = {
    name: 'Paybswap',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.PAYB,
    displaySymbol: 'PAYB',
    slug: 'paybswap',
    address: contracts_1.PAYBSWAPAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/payb.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('paybswap'),
    priceSourceIds: {
        coinMarketCap: 8942,
        coinGecko: 'paybswap',
        // not listed on cryptoCompare
    },
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.PAYB, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD])],
};
const landToken = {
    name: 'Landshare',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.LAND,
    displaySymbol: 'LAND',
    slug: 'landshare',
    address: contracts_1.LANDAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/land.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('landshare'),
    priceSourceIds: {
        coinMarketCap: 11245,
        coinGecko: 'landshare',
        // not listed on cryptoCompare
    },
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.LAND, entity_2.TokenSymbol.WBNB, entity_2.TokenSymbol.BUSD])],
};
const highToken = {
    name: 'HighStreet',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.HIGH,
    displaySymbol: 'HIGH',
    slug: 'highstreet',
    address: contracts_1.HIGHAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/high.svg',
    buyUrl: 'https://pancakeswap.finance/swap?outputCurrency=0x5f4bde007dc06b867f86ebfe4802e34a1ffeed63',
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('highstreet'),
    priceSourceIds: {
        coinMarketCap: 11232,
        coinGecko: 'highstreet',
        cryptoCompare: entity_2.TokenSymbol.HIGH,
    },
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.HIGH, entity_2.TokenSymbol.BUSD])],
};
const dltaToken = {
    name: 'Delta Thetha',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.DLTA,
    displaySymbol: 'DLTA',
    slug: 'delta-theta',
    address: contracts_1.DLTAAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/dlta.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('delta-theta'),
    priceSourceIds: {
        coinMarketCap: 11341,
        coinGecko: 'delta-theta',
        // not listed on cryptoCompare
    },
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.DLTA, entity_2.TokenSymbol.BUSD])],
};
// IB Tokens
const ibBNBToken = {
    name: 'ibBNB',
    type: entity_2.TokenType.InterestBearing,
    symbol: entity_2.TokenSymbol.IBBNB,
    displaySymbol: 'ibBNB',
    slug: '',
    address: contracts_1.BNBVaultAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/ib-bnb.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: fiatPrice_1.getZero,
    underlyingToken: bnbToken,
    priceSourceIds: {},
};
const ibBUSDToken = {
    name: 'ibBUSD',
    type: entity_2.TokenType.InterestBearing,
    symbol: entity_2.TokenSymbol.IBBUSD,
    displaySymbol: 'ibBUSD',
    slug: '',
    address: contracts_1.BUSDVaultAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/ib-busd.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: fiatPrice_1.getZero,
    underlyingToken: busdToken,
    priceSourceIds: {},
};
const ibETHToken = {
    name: 'ibETH',
    type: entity_2.TokenType.InterestBearing,
    symbol: entity_2.TokenSymbol.IBETH,
    displaySymbol: 'ibETH',
    slug: '',
    address: contracts_1.ETHVaultAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/ib-eth.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: fiatPrice_1.getZero,
    underlyingToken: ethToken,
    priceSourceIds: {},
};
const ibALPACAToken = {
    name: 'ibALPACA',
    type: entity_2.TokenType.InterestBearing,
    symbol: entity_2.TokenSymbol.IBALPACA,
    displaySymbol: 'ibALPACA',
    slug: '',
    address: contracts_1.ALPACAVaultAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/ib-alpaca.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: fiatPrice_1.getZero,
    underlyingToken: alpacaToken,
    priceSourceIds: {},
};
const ibUSDTToken = {
    name: 'ibUSDT',
    type: entity_2.TokenType.InterestBearing,
    symbol: entity_2.TokenSymbol.IBUSDT,
    displaySymbol: 'ibUSDT',
    slug: '',
    address: contracts_1.USDTVaultAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/ib-usdt.svg?v=2',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: fiatPrice_1.getZero,
    underlyingToken: usdtToken,
    priceSourceIds: {},
};
const ibBTCBToken = {
    name: 'ibBTCB',
    type: entity_2.TokenType.InterestBearing,
    symbol: entity_2.TokenSymbol.IBBTCB,
    displaySymbol: 'ibBTCB',
    slug: '',
    address: contracts_1.BTCBVaultAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/ib-btcb.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: fiatPrice_1.getZero,
    underlyingToken: btcbToken,
    priceSourceIds: {},
};
const ibTUSDToken = {
    name: 'ibTUSD',
    type: entity_2.TokenType.InterestBearing,
    symbol: entity_2.TokenSymbol.IBTUSD,
    displaySymbol: 'ibTUSD',
    slug: '',
    address: contracts_1.TUSDVaultAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/ib-tusd.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: fiatPrice_1.getZero,
    underlyingToken: tusdToken,
    priceSourceIds: {},
};
const ibUSDCToken = {
    name: 'ibUSDC',
    type: entity_2.TokenType.InterestBearing,
    symbol: entity_2.TokenSymbol.IBUSDC,
    displaySymbol: 'ibUSDC',
    slug: '',
    address: contracts_1.USDCVaultAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/ib-usdc.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: fiatPrice_1.getZero,
    underlyingToken: usdcToken,
    priceSourceIds: {},
};
// Debt Tokens
const debtBNBToken = {
    name: 'debtBNB',
    type: entity_2.TokenType.Debt,
    symbol: entity_2.TokenSymbol.DEBTBNB,
    displaySymbol: 'debtBNB',
    slug: '',
    address: contracts_1.DebtTokenBNBAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/bnb.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: fiatPrice_1.getZero,
    underlyingToken: bnbToken,
    priceSourceIds: {},
};
const debtBUSDToken = {
    name: 'debtBUSD',
    type: entity_2.TokenType.Debt,
    symbol: entity_2.TokenSymbol.DEBTBUSD,
    displaySymbol: 'debtBUSD',
    slug: '',
    address: contracts_1.DebtTokenBUSDAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/busd.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: fiatPrice_1.getZero,
    underlyingToken: busdToken,
    priceSourceIds: {},
};
const debtETHToken = {
    name: 'debtETH',
    type: entity_2.TokenType.Debt,
    symbol: entity_2.TokenSymbol.DEBTETH,
    displaySymbol: 'debtETH',
    slug: '',
    address: contracts_1.DebtTokenETHAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/eth.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: fiatPrice_1.getZero,
    underlyingToken: ethToken,
    priceSourceIds: {},
};
const debtALPACAToken = {
    name: 'debtALPACA',
    type: entity_2.TokenType.Debt,
    symbol: entity_2.TokenSymbol.DEBTALPACA,
    displaySymbol: 'debtALPACA',
    slug: '',
    address: contracts_1.DebtTokenALPACAAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/alpaca.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: fiatPrice_1.getZero,
    underlyingToken: alpacaToken,
    priceSourceIds: {},
};
const debtUSDTToken = {
    name: 'debtUSDT',
    type: entity_2.TokenType.Debt,
    symbol: entity_2.TokenSymbol.DEBTUSDT,
    displaySymbol: 'debtUSDT',
    slug: '',
    address: contracts_1.DebtTokenUSDTAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/usdt.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: fiatPrice_1.getZero,
    underlyingToken: usdtToken,
    priceSourceIds: {},
};
const debtBTCBToken = {
    name: 'debtBTCB',
    type: entity_2.TokenType.Debt,
    symbol: entity_2.TokenSymbol.DEBTBTCB,
    displaySymbol: 'debtBTCB',
    slug: '',
    address: contracts_1.DebtTokenBTCBAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/btcb.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: fiatPrice_1.getZero,
    underlyingToken: btcbToken,
    priceSourceIds: {},
};
const debtTUSDToken = {
    name: 'debtTUSD',
    type: entity_2.TokenType.Debt,
    symbol: entity_2.TokenSymbol.DEBTTUSD,
    displaySymbol: 'debtTUSD',
    slug: '',
    address: contracts_1.DebtTokenTUSDAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/tusd.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: fiatPrice_1.getZero,
    underlyingToken: tusdToken,
    priceSourceIds: {},
};
const debtUSDCToken = {
    name: 'debtUSDC',
    type: entity_2.TokenType.Debt,
    symbol: entity_2.TokenSymbol.DEBTUSDC,
    displaySymbol: 'debtUSDC',
    slug: '',
    address: contracts_1.DebtTokenUSDCAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/usdc.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: fiatPrice_1.getZero,
    underlyingToken: usdcToken,
    priceSourceIds: {},
};
// Alpaca Stablecoin
const ausdToken = {
    name: 'Alpaca USD',
    type: entity_2.TokenType.Common,
    symbol: entity_2.TokenSymbol.AUSD,
    displaySymbol: 'AUSD',
    slug: 'ausd',
    address: ausdContracts_1.AUSDAddress,
    iconUrl: 'https://alpaca-app-assets.alpacafinance.org/icons/coins/ausd.svg',
    buyUrl: undefined,
    decimal: 18,
    isTokenNative: false,
    getPriceInUSD: () => fiatPrice_1.getTokenPrice('ausd'),
    priceSourceIds: {},
    priceRoutes: [entity_2.ILPRouteV2Factory.createILPFromPcsV2Route([entity_2.TokenSymbol.AUSD, entity_2.TokenSymbol.BUSD])],
};
exports.tokenProfiles = [
    bnbToken,
    busdToken,
    ethToken,
    btcbToken,
    cakeToken,
    usdtToken,
    dotToken,
    uniToken,
    linkToken,
    xvsToken,
    yfiToken,
    vaiToken,
    usdcToken,
    daiToken,
    ustToken,
    itamToken,
    bethToken,
    compToken,
    sushiToken,
    alpacaToken,
    sAlpacaToken,
    ibBNBToken,
    ibBUSDToken,
    ibETHToken,
    ibALPACAToken,
    ibUSDTToken,
    ibBTCBToken,
    ibTUSDToken,
    ibUSDCToken,
    debtBNBToken,
    debtBUSDToken,
    debtETHToken,
    debtUSDTToken,
    debtALPACAToken,
    debtBTCBToken,
    debtTUSDToken,
    debtUSDCToken,
    ausdToken,
    bmxxToken,
    beltToken,
    borToken,
    bryToken,
    pcwsToken,
    swingbyToken,
    dodoToken,
    wexToken,
    waultxToken,
    oddzToken,
    adaToken,
    formToken,
    maticToken,
    tusdToken,
    trxToken,
    bttToken,
    orbsToken,
    axsToken,
    pmonToken,
    scixToken,
    wusdToken,
    phaToken,
    almToken,
    kalaToken,
    mboxToken,
    naosToken,
    mdxToken,
    dviToken,
    latteToken,
    qbtToken,
    pearToken,
    potsToken,
    luckyToken,
    polarToken,
    moniToken,
    bmonToken,
    nftyToken,
    sheeshaToken,
    skillToken,
    xmsToken,
    arvToken,
    xwinToken,
    leonToken,
    wnowToken,
    depToken,
    tenfiToken,
    capsToken,
    spsToken,
    plutToken,
    eternalToken,
    thgToken,
    paybSwapToken,
    landToken,
    highToken,
    dltaToken,
];
exports.mapTokenProfiles = exports.tokenProfiles.reduce((accu, token) => {
    return Object.assign(Object.assign({}, accu), { [token.symbol]: token });
}, {});
exports.mapAddressTokenProfiles = exports.tokenProfiles.reduce((accu, token) => {
    return Object.assign(Object.assign({}, accu), { [token.address.toLowerCase()]: token });
}, {});
const pcsAlpacaWbnb = {
    name: 'PancakeSwap ALPACA-WBNB',
    tokenA: bnbToken,
    tokenB: alpacaToken,
    dex: entity_1.PancakeSwapDex,
    type: entity_2.TokenType.LpPair,
};
const pcsAusdBusd = {
    name: 'PancakeSwap AUSD-BUSD',
    tokenA: busdToken,
    tokenB: ausdToken,
    dex: entity_1.PancakeSwapDex,
    type: entity_2.TokenType.LpPair,
};
const pcsV1AlpacaWbnb = {
    name: 'PancakeSwapV1 ALPACA-WBNB',
    tokenA: bnbToken,
    tokenB: alpacaToken,
    dex: entity_1.PancakeSwapDexV1,
    type: entity_2.TokenType.LpPair,
};
exports.lpTokenProfiles = [pcsAlpacaWbnb, pcsV1AlpacaWbnb];
exports.mapLpTokenProfiles = {
    [entity_1.DexKey.PancakeSwap]: {
        [entity_2.TokenSymbol.ALPACA]: {
            [entity_2.TokenSymbol.WBNB]: pcsAlpacaWbnb,
        },
        [entity_2.TokenSymbol.WBNB]: {
            [entity_2.TokenSymbol.ALPACA]: pcsAlpacaWbnb,
        },
        [entity_2.TokenSymbol.AUSD]: {
            [entity_2.TokenSymbol.BUSD]: pcsAusdBusd,
        },
        [entity_2.TokenSymbol.BUSD]: {
            [entity_2.TokenSymbol.AUSD]: pcsAusdBusd,
        },
    },
    [entity_1.DexKey.PancakeSwapV1]: {
        [entity_2.TokenSymbol.ALPACA]: {
            [entity_2.TokenSymbol.WBNB]: pcsV1AlpacaWbnb,
        },
        [entity_2.TokenSymbol.WBNB]: {
            [entity_2.TokenSymbol.ALPACA]: pcsV1AlpacaWbnb,
        },
    },
    [entity_1.DexKey.WaultSwap]: {},
    [entity_1.DexKey.MdexSwap]: {},
};
function getLpTokenAddress(lpToken) {
    const iLpRoute = entity_2.ILPRouteV2Factory.createILPRouteV2([lpToken.tokenA, lpToken.tokenB], lpToken.dex.factory);
    if (!iLpRoute)
        return '';
    const [lpAddress] = new entity_1.LPRouteV2(iLpRoute, exports.mapTokenProfiles).getLPPaths();
    return lpAddress;
}
exports.getLpTokenAddress = getLpTokenAddress;
function getTokenAddress(token) {
    if (token.type === entity_2.TokenType.LpPair) {
        return getLpTokenAddress(token);
    }
    return token.address;
}
exports.getTokenAddress = getTokenAddress;
function getDisplaySymbol(token) {
    if (token.type !== entity_2.TokenType.LpPair) {
        return token.displaySymbol;
    }
    const { tokenA, tokenB, dex } = token;
    return `${tokenB.displaySymbol}-${tokenA.displaySymbol} ${dex.key.toUpperCase()} LP`;
}
exports.getDisplaySymbol = getDisplaySymbol;
