/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IShield, IShieldInterface } from "../IShield";

const _abi = [
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IShield__factory {
  static readonly abi = _abi;
  static createInterface(): IShieldInterface {
    return new utils.Interface(_abi) as IShieldInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IShield {
    return new Contract(address, _abi, signerOrProvider) as IShield;
  }
}
