"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PositionHandler__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "_bookKeeper",
                type: "address",
            },
        ],
        stateMutability: "nonpayable",
        type: "constructor",
    },
];
const _bytecode = "0x6080604052348015600f57600080fd5b5060405160db38038060db83398181016040526020811015602f57600080fd5b505160408051634d8c928d60e11b815233600482015290516001600160a01b03831691639b19251a91602480830192600092919082900301818387803b158015607757600080fd5b505af1158015608a573d6000803e3d6000fd5b5050505050603f80609c6000396000f3fe6080604052600080fdfea26469706673582212209004034dee5cdddfbbce767345f04d7e39bc7dd683ca291ec464efc93fa197a564736f6c634300060c0033";
const isSuperArgs = (xs) => xs.length > 1;
class PositionHandler__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    deploy(_bookKeeper, overrides) {
        return super.deploy(_bookKeeper, overrides || {});
    }
    getDeployTransaction(_bookKeeper, overrides) {
        return super.getDeployTransaction(_bookKeeper, overrides || {});
    }
    attach(address) {
        return super.attach(address);
    }
    connect(signer) {
        return super.connect(signer);
    }
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.PositionHandler__factory = PositionHandler__factory;
PositionHandler__factory.bytecode = _bytecode;
PositionHandler__factory.abi = _abi;
