"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IWorkerConfig__factory = void 0;
const ethers_1 = require("ethers");
class IWorkerConfig__factory {
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.IWorkerConfig__factory = IWorkerConfig__factory;
const _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "worker",
                type: "address",
            },
        ],
        name: "acceptDebt",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "worker",
                type: "address",
            },
        ],
        name: "isReserveConsistent",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "worker",
                type: "address",
            },
        ],
        name: "isStable",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "worker",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "debt",
                type: "uint256",
            },
        ],
        name: "killFactor",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "worker",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "debt",
                type: "uint256",
            },
        ],
        name: "rawKillFactor",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "worker",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "debt",
                type: "uint256",
            },
        ],
        name: "workFactor",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
