/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface AlpacaFeederInterface extends ethers.utils.Interface {
  functions: {
    "fairLaunch()": FunctionFragment;
    "fairLaunchDeposit()": FunctionFragment;
    "fairLaunchHarvest()": FunctionFragment;
    "fairLaunchPoolId()": FunctionFragment;
    "fairLaunchWithdraw()": FunctionFragment;
    "feedGrassHouse()": FunctionFragment;
    "grassHouse()": FunctionFragment;
    "initialize(address,address,address,uint256,address)": FunctionFragment;
    "owner()": FunctionFragment;
    "proxyToken()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "token()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "fairLaunch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fairLaunchDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fairLaunchHarvest",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fairLaunchPoolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fairLaunchWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feedGrassHouse",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grassHouse",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxyToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "fairLaunch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fairLaunchDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fairLaunchHarvest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fairLaunchPoolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fairLaunchWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feedGrassHouse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grassHouse", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "proxyToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "LogFairLaunchDeposit()": EventFragment;
    "LogFairLaunchHarvest(address,uint256)": EventFragment;
    "LogFairLaunchWithdraw()": EventFragment;
    "LogFeedGrassHouse(uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LogFairLaunchDeposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogFairLaunchHarvest"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogFairLaunchWithdraw"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogFeedGrassHouse"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class AlpacaFeeder extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: AlpacaFeederInterface;

  functions: {
    fairLaunch(overrides?: CallOverrides): Promise<[string]>;

    "fairLaunch()"(overrides?: CallOverrides): Promise<[string]>;

    fairLaunchDeposit(overrides?: Overrides): Promise<ContractTransaction>;

    "fairLaunchDeposit()"(overrides?: Overrides): Promise<ContractTransaction>;

    fairLaunchHarvest(overrides?: Overrides): Promise<ContractTransaction>;

    "fairLaunchHarvest()"(overrides?: Overrides): Promise<ContractTransaction>;

    fairLaunchPoolId(overrides?: CallOverrides): Promise<[BigNumber]>;

    "fairLaunchPoolId()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    fairLaunchWithdraw(overrides?: Overrides): Promise<ContractTransaction>;

    "fairLaunchWithdraw()"(overrides?: Overrides): Promise<ContractTransaction>;

    feedGrassHouse(overrides?: Overrides): Promise<ContractTransaction>;

    "feedGrassHouse()"(overrides?: Overrides): Promise<ContractTransaction>;

    grassHouse(overrides?: CallOverrides): Promise<[string]>;

    "grassHouse()"(overrides?: CallOverrides): Promise<[string]>;

    initialize(
      _token: string,
      _proxyToken: string,
      _fairLaunchAddress: string,
      _fairLaunchPoolId: BigNumberish,
      _grasshouseAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(address,address,address,uint256,address)"(
      _token: string,
      _proxyToken: string,
      _fairLaunchAddress: string,
      _fairLaunchPoolId: BigNumberish,
      _grasshouseAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    proxyToken(overrides?: CallOverrides): Promise<[string]>;

    "proxyToken()"(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    token(overrides?: CallOverrides): Promise<[string]>;

    "token()"(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  fairLaunch(overrides?: CallOverrides): Promise<string>;

  "fairLaunch()"(overrides?: CallOverrides): Promise<string>;

  fairLaunchDeposit(overrides?: Overrides): Promise<ContractTransaction>;

  "fairLaunchDeposit()"(overrides?: Overrides): Promise<ContractTransaction>;

  fairLaunchHarvest(overrides?: Overrides): Promise<ContractTransaction>;

  "fairLaunchHarvest()"(overrides?: Overrides): Promise<ContractTransaction>;

  fairLaunchPoolId(overrides?: CallOverrides): Promise<BigNumber>;

  "fairLaunchPoolId()"(overrides?: CallOverrides): Promise<BigNumber>;

  fairLaunchWithdraw(overrides?: Overrides): Promise<ContractTransaction>;

  "fairLaunchWithdraw()"(overrides?: Overrides): Promise<ContractTransaction>;

  feedGrassHouse(overrides?: Overrides): Promise<ContractTransaction>;

  "feedGrassHouse()"(overrides?: Overrides): Promise<ContractTransaction>;

  grassHouse(overrides?: CallOverrides): Promise<string>;

  "grassHouse()"(overrides?: CallOverrides): Promise<string>;

  initialize(
    _token: string,
    _proxyToken: string,
    _fairLaunchAddress: string,
    _fairLaunchPoolId: BigNumberish,
    _grasshouseAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(address,address,address,uint256,address)"(
    _token: string,
    _proxyToken: string,
    _fairLaunchAddress: string,
    _fairLaunchPoolId: BigNumberish,
    _grasshouseAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  proxyToken(overrides?: CallOverrides): Promise<string>;

  "proxyToken()"(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  token(overrides?: CallOverrides): Promise<string>;

  "token()"(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    fairLaunch(overrides?: CallOverrides): Promise<string>;

    "fairLaunch()"(overrides?: CallOverrides): Promise<string>;

    fairLaunchDeposit(overrides?: CallOverrides): Promise<void>;

    "fairLaunchDeposit()"(overrides?: CallOverrides): Promise<void>;

    fairLaunchHarvest(overrides?: CallOverrides): Promise<void>;

    "fairLaunchHarvest()"(overrides?: CallOverrides): Promise<void>;

    fairLaunchPoolId(overrides?: CallOverrides): Promise<BigNumber>;

    "fairLaunchPoolId()"(overrides?: CallOverrides): Promise<BigNumber>;

    fairLaunchWithdraw(overrides?: CallOverrides): Promise<void>;

    "fairLaunchWithdraw()"(overrides?: CallOverrides): Promise<void>;

    feedGrassHouse(overrides?: CallOverrides): Promise<void>;

    "feedGrassHouse()"(overrides?: CallOverrides): Promise<void>;

    grassHouse(overrides?: CallOverrides): Promise<string>;

    "grassHouse()"(overrides?: CallOverrides): Promise<string>;

    initialize(
      _token: string,
      _proxyToken: string,
      _fairLaunchAddress: string,
      _fairLaunchPoolId: BigNumberish,
      _grasshouseAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(address,address,address,uint256,address)"(
      _token: string,
      _proxyToken: string,
      _fairLaunchAddress: string,
      _fairLaunchPoolId: BigNumberish,
      _grasshouseAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    proxyToken(overrides?: CallOverrides): Promise<string>;

    "proxyToken()"(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    token(overrides?: CallOverrides): Promise<string>;

    "token()"(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    LogFairLaunchDeposit(): EventFilter;

    LogFairLaunchHarvest(_caller: null, _harvestAmount: null): EventFilter;

    LogFairLaunchWithdraw(): EventFilter;

    LogFeedGrassHouse(_feedAmount: null): EventFilter;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;
  };

  estimateGas: {
    fairLaunch(overrides?: CallOverrides): Promise<BigNumber>;

    "fairLaunch()"(overrides?: CallOverrides): Promise<BigNumber>;

    fairLaunchDeposit(overrides?: Overrides): Promise<BigNumber>;

    "fairLaunchDeposit()"(overrides?: Overrides): Promise<BigNumber>;

    fairLaunchHarvest(overrides?: Overrides): Promise<BigNumber>;

    "fairLaunchHarvest()"(overrides?: Overrides): Promise<BigNumber>;

    fairLaunchPoolId(overrides?: CallOverrides): Promise<BigNumber>;

    "fairLaunchPoolId()"(overrides?: CallOverrides): Promise<BigNumber>;

    fairLaunchWithdraw(overrides?: Overrides): Promise<BigNumber>;

    "fairLaunchWithdraw()"(overrides?: Overrides): Promise<BigNumber>;

    feedGrassHouse(overrides?: Overrides): Promise<BigNumber>;

    "feedGrassHouse()"(overrides?: Overrides): Promise<BigNumber>;

    grassHouse(overrides?: CallOverrides): Promise<BigNumber>;

    "grassHouse()"(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _token: string,
      _proxyToken: string,
      _fairLaunchAddress: string,
      _fairLaunchPoolId: BigNumberish,
      _grasshouseAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(address,address,address,uint256,address)"(
      _token: string,
      _proxyToken: string,
      _fairLaunchAddress: string,
      _fairLaunchPoolId: BigNumberish,
      _grasshouseAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    proxyToken(overrides?: CallOverrides): Promise<BigNumber>;

    "proxyToken()"(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    token(overrides?: CallOverrides): Promise<BigNumber>;

    "token()"(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    fairLaunch(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "fairLaunch()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fairLaunchDeposit(overrides?: Overrides): Promise<PopulatedTransaction>;

    "fairLaunchDeposit()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    fairLaunchHarvest(overrides?: Overrides): Promise<PopulatedTransaction>;

    "fairLaunchHarvest()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    fairLaunchPoolId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "fairLaunchPoolId()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fairLaunchWithdraw(overrides?: Overrides): Promise<PopulatedTransaction>;

    "fairLaunchWithdraw()"(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    feedGrassHouse(overrides?: Overrides): Promise<PopulatedTransaction>;

    "feedGrassHouse()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    grassHouse(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "grassHouse()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      _token: string,
      _proxyToken: string,
      _fairLaunchAddress: string,
      _fairLaunchPoolId: BigNumberish,
      _grasshouseAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(address,address,address,uint256,address)"(
      _token: string,
      _proxyToken: string,
      _fairLaunchAddress: string,
      _fairLaunchPoolId: BigNumberish,
      _grasshouseAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proxyToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "proxyToken()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    token(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "token()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
