/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IGrassHouseInterface extends ethers.utils.Interface {
  functions: {
    "claim(address)": FunctionFragment;
    "feed(uint256)": FunctionFragment;
    "rewardToken()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "claim", values: [string]): string;
  encodeFunctionData(functionFragment: "feed", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "rewardToken",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "feed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rewardToken",
    data: BytesLike
  ): Result;

  events: {};
}

export class IGrassHouse extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IGrassHouseInterface;

  functions: {
    claim(_for: string, overrides?: Overrides): Promise<ContractTransaction>;

    "claim(address)"(
      _for: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    feed(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "feed(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    rewardToken(overrides?: Overrides): Promise<ContractTransaction>;

    "rewardToken()"(overrides?: Overrides): Promise<ContractTransaction>;
  };

  claim(_for: string, overrides?: Overrides): Promise<ContractTransaction>;

  "claim(address)"(
    _for: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  feed(
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "feed(uint256)"(
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  rewardToken(overrides?: Overrides): Promise<ContractTransaction>;

  "rewardToken()"(overrides?: Overrides): Promise<ContractTransaction>;

  callStatic: {
    claim(_for: string, overrides?: CallOverrides): Promise<BigNumber>;

    "claim(address)"(
      _for: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    feed(_amount: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

    "feed(uint256)"(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    rewardToken(overrides?: CallOverrides): Promise<string>;

    "rewardToken()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    claim(_for: string, overrides?: Overrides): Promise<BigNumber>;

    "claim(address)"(_for: string, overrides?: Overrides): Promise<BigNumber>;

    feed(_amount: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "feed(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    rewardToken(overrides?: Overrides): Promise<BigNumber>;

    "rewardToken()"(overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    claim(_for: string, overrides?: Overrides): Promise<PopulatedTransaction>;

    "claim(address)"(
      _for: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    feed(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "feed(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    rewardToken(overrides?: Overrides): Promise<PopulatedTransaction>;

    "rewardToken()"(overrides?: Overrides): Promise<PopulatedTransaction>;
  };
}
